paylogic/urls.py
import sys
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views import debug

from paylogic import patches  # NOQA
from paylogic import lookups

# from codereview.urls import urlpatterns

admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',   # There two are to
        {'document_root': 'static/'}),                  # fix the migration
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',  # from Django 1.1 to 1.3
        {'document_root': 'static/'}),                  # because of contrib.staticfiles
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='auth_login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login', name='auth_logout'),
    url(r'^fogbugz/authorize/?$', 'paylogic.views.fogbugz_authorize', name='fogbugz_authorize'),
    ('^admin/', include(admin.site.urls)),
    (r'^openid/', include('django_openid_auth.urls')),
    ('^_ah/admin', 'rietveld_helper.views.admin_redirect'),
    url(r'^(\d+)/publish$', 'paylogic.views.publish'),
    url(r'^fogbugz$', 'paylogic.views.process_codereview_from_fogbugz',
        name='process_from_fogbugz'),
    url(r'^fogbugz_find$', 'paylogic.views.find_codereview_from_fogbugz',
        name='find_from_fogbugz'),
    url(r'^mergekeeper_close/(?P<case_id>\d+)/$',
        'paylogic.views.mergekeeper_close', name='mergekeeper_close'),
    url(r'^lookup/target_branches/(?P<case_id>\d+)$',
        lookups.TargetBranchesView.as_view(), name='lookup_target_branches'),
    url(r'^gatekeeper_mark_ok/(?P<issue_id>\d+)/$',
        'paylogic.views.gatekeeper_mark_ok', name="paylogic_mark_ok"),
    url(r'^lookup/case_assigned/(?P<case_id>\d+)$',
        lookups.CaseAssignedView.as_view(), name='lookup_case_assigned'),
    url(r'^lookup/tags/(?P<case_id>\d+)?$',
        lookups.TagsView.as_view(), name='lookup_tags'),
    ('', include('codereview.urls')),
)

handler500 = lambda request: debug.technical_500_response(
    request, *sys.exc_info())

import paylogic.measurements

paylogic.measurements.set_timers('paylogic.views')
paylogic.measurements.set_timers('codereview.views')

codereview/models.py
# Copyright 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""App Engine data model (schema) definition for Rietveld."""

import logging
from hashlib import md5
import os
import re
import time

from google.appengine.ext import db
from google.appengine.api import memcache
from google.appengine.api import users

from django.utils.encoding import force_unicode

import engine
import patching


CONTEXT_CHOICES = (3, 10, 25, 50, 75, 100)


# GQL query cache ###


_query_cache = {}


def gql(cls, clause, *args, **kwds):
    """Return a query object, from the cache if possible.

    Args:
      cls: a db.Model subclass.
      clause: a query clause, e.g. 'WHERE draft = TRUE'.
      *args, **kwds: positional and keyword arguments to be bound to the query.

    Returns:
      A db.GqlQuery instance corresponding to the query with *args and
      **kwds bound to the query.
    """
    query_string = 'SELECT * FROM %s %s' % (cls.kind(), clause)
    query = _query_cache.get(query_string)
    if query is None:
        _query_cache[query_string] = query = db.GqlQuery(query_string)
    query.bind(*args, **kwds)
    return query


# Issues, PatchSets, Patches, Contents, Comments, Messages ###


class Issue(db.Model):

    """The major top-level entity.

    It has one or more PatchSets as its descendants.
    """

    subject = db.StringProperty(required=True)
    description = db.TextProperty()
    #: in Subversion - repository path (URL) for files in patch set
    base = db.StringProperty()
    #: if True then base files for patches were uploaded with upload.py
    #: (if False - then Rietveld attempts to download them from server)
    local_base = db.BooleanProperty(default=False)
    repo_guid = db.StringProperty()
    owner = db.UserProperty(auto_current_user_add=True, required=True)
    created = db.DateTimeProperty(auto_now_add=True)
    modified = db.DateTimeProperty(auto_now=True)
    reviewers = db.ListProperty(db.Email)
    cc = db.ListProperty(db.Email)
    closed = db.BooleanProperty(default=False)
    private = db.BooleanProperty(default=False)
    n_comments = db.IntegerProperty()

    latest_patch_rev = db.StringProperty(required=False)
    latest_reviewed_rev = db.StringProperty(required=False)
    processing = db.BooleanProperty(default=False)

    _is_starred = None

    class Meta:
        permissions = (
            ("view_issue", "View issue"),
        )

    @property
    def is_starred(self):
        """Whether the current user has this issue starred."""
        if self._is_starred is not None:
            return self._is_starred
        account = Account.current_user_account
        self._is_starred = account is not None and self.key(
        ).id() in account.stars
        return self._is_starred

    def user_can_edit(self, user):
        """Return true if the given user has permission to edit this issue."""
        return user == self.owner or user.has_perm('codereview.change_issue')

    @property
    def edit_allowed(self):
        """Whether the current user can edit this issue."""
        account = Account.current_user_account
        if account is None:
            return False
        return self.user_can_edit(account.user)

    def update_comment_count(self, n):
        """Increment the n_comments property by n.

        If n_comments in None, compute the count through a query.  (This
        is a transitional strategy while the database contains Issues
        created using a previous version of the schema.)
        """
        if self.n_comments is None:
            self.n_comments = self._get_num_comments()
        self.n_comments += n

    @property
    def num_comments(self):
        """The number of non-draft comments for this issue.

        This is almost an alias for self.n_comments, except that if
        n_comments is None, it is computed through a query, and stored,
        using n_comments as a cache.
        """
        if self.n_comments is None:
            self.n_comments = self._get_num_comments()
        return self.n_comments

    def _get_num_comments(self):
        """Helper to compute the number of comments through a query."""
        return gql(Comment,
                   'WHERE ANCESTOR IS :1 AND draft = FALSE',
                   self).count()

    _num_drafts = None

    @property
    def num_drafts(self):
        """The number of draft comments on this issue for the current user.

        The value is expensive to compute, so it is cached.
        """
        if self._num_drafts is None:
            account = Account.current_user_account
            if account is None:
                self._num_drafts = 0
            else:
                query = gql(Comment,
                            'WHERE ANCESTOR IS :1 AND author = :2 AND draft = TRUE',
                            self, account.user)
                self._num_drafts = query.count()
        return self._num_drafts

    @property
    def patchsets(self):
        """Get issue patchsets in order."""
        return self.patchset_set.order('created')

    @property
    def latest_patchset(self):
        """Get latest patchset."""
        try:
            return self.patchsets.reverse()[0]
        except IndexError:
            return None

    @property
    def latest_patchset_number(self):
        """Get latest patchset number."""
        try:
            return list(self.patchsets).index(self.latest_patchset) + 1
        except ValueError:
            return None

    @property
    def latest_approved_patchset(self):
        """Get latest approved patchset."""
        if self.latest_reviewed_rev:
            try:
                return self.patchsets.reverse().filter(revision=self.latest_reviewed_rev)[0]
            except IndexError:
                return None

    @property
    def latest_approved_patchset_number(self):
        """Get latest approved patchset number."""
        try:
            return list(self.patchsets).index(self.latest_approved_patchset) + 1
        except ValueError:
            return None


class PatchSet(db.Model):

    """A set of patchset uploaded together.

    This is a descendant of an Issue and has Patches as descendants.
    """

    issue = db.ReferenceProperty(Issue)  # == parent
    message = db.StringProperty()
    data = db.TextProperty()  # blob
    url = db.LinkProperty()
    created = db.DateTimeProperty(auto_now_add=True)
    modified = db.DateTimeProperty(auto_now=True)
    n_comments = db.IntegerProperty(default=0)
    revision = db.StringProperty(required=False)

    class Meta:
        permissions = (
            ("approve_patchset", "Approve patchset"),
        )

    def update_comment_count(self, n):
        """Increment the n_comments property by n."""
        self.n_comments = self.num_comments + n

    @property
    def num_comments(self):
        """The number of non-draft comments for this issue.

        This is almost an alias for self.n_comments, except that if
        n_comments is None, 0 is returned.
        """
        # For older patchsets n_comments is None.
        return self.n_comments or 0


class Message(db.Model):

    """A copy of a message sent out in email.

    This is a descendant of an Issue.
    """

    issue = db.ReferenceProperty(Issue)  # == parent
    subject = db.StringProperty()
    sender = db.EmailProperty()
    recipients = db.ListProperty(db.Email)
    date = db.DateTimeProperty(auto_now_add=True)
    text = db.TextProperty()
    draft = db.BooleanProperty(default=False)

    _approval = None

    @property
    def approval(self):
        """Is True when the message represents an approval of the review."""
        if self._approval is None:
            # Must contain 'lgtm' in a line that doesn't start with '>'.
            self._approval = any(
                True for line in self.text.lower().splitlines()
                if not line.strip().startswith('>') and 'lgtm' in line)
            # Must not be issue owner.
            self._approval &= self.issue.owner.email() != self.sender
        return self._approval


class Content(db.Model):

    """The content of a text file.

    This is a descendant of a Patch.
    """

    # parent => Patch
    text = db.TextProperty()
    data = db.TextProperty()  # blob
    # Checksum over text or data depending on the type of this content.
    checksum = db.TextProperty()
    is_uploaded = db.BooleanProperty(default=False)
    is_bad = db.BooleanProperty(default=False)
    file_too_large = db.BooleanProperty(default=False)

    @property
    def lines(self):
        """The text split into lines, retaining line endings."""
        if not self.text:
            return []
        return self.text.splitlines(True)


class Patch(db.Model):

    """A single patch, i.e. a set of changes to a single file.

    This is a descendant of a PatchSet.
    """

    patchset = db.ReferenceProperty(PatchSet)  # == parent
    filename = db.StringProperty()
    old_filename = db.StringProperty()
    status = db.StringProperty()  # 'A', 'A  +', 'M', 'D' etc
    text = db.TextProperty()
    content = db.ReferenceProperty(Content)
    patched_content = db.ReferenceProperty(
        Content, collection_name='patch2_set')
    is_binary = db.BooleanProperty(default=False)
    # Ids of patchsets that have a different version of this file.
    delta = db.ListProperty(int)
    delta_calculated = db.BooleanProperty(default=False)

    _lines = None

    @property
    def lines(self):

templates/all.html
{%extends "issue_pagination.html"%}
{%block subtitle%}Recent Issues {%if closed%}(including closed){%endif%}{%endblock%}

templates/diff_missing.html
{%extends "issue_base.html"%}
{%block body%}

<script language="JavaScript" type="text/javascript"><!--
document.onkeydown = M_keyDown;
{%if user%}
logged_in = true;
{%else%}
logged_in = false;
login_warned = false;
{%endif%}
// -->
</script>

<div style="float: left;">
  <h2 style="margin-bottom: 0em; margin-top: 0em;">Side by Side diff: {{ filename }}</h2>
  <div style="margin-top: .2em;">{%include "issue_star.html"%}
    <b>Issue <a href="{%url codereview.views.show issue.key.id%}" onmouseover="M_showPopUp(this, 'popup-issue');" id="upCL">{{issue.key.id}}</a>:</b>
  {{issue.subject}} {%if issue.closed %} (Closed) {%endif%}
  {%if issue.base%}<span class="extra">Base URL: {{issue.base}}</span>{%endif%}</div>
  <div style="margin-top: .4em;">
    <b>Patch Set: {%if patchset.message%}{{patchset.message}}{%endif%}</b>
    <span class="extra">
    Created {{patchset.created|timesince}} ago
    {%if patchset.url%},
    Downloaded from: <a href="{{patchset.url}}">{{patchset.url}}</a>
    {%endif%}
    </span>
  </div>
  <div style="margin-top: .4em">
    <table>
      <tr>
        <td>Left:</td>
        <td>
          <select name="left" id="left">
            <option value="-1">Base</option>
            {%for p in patchsets%}
            <option value="{{p.key.id}}">Patch Set {{forloop.counter}}: {{p.message}}</option>
            {%endfor%}
          </select>
        </td>
        <td rowspan="2"><input type="button" value="Go" onclick="M_navigateDiff({{issue.key.id}}, '{{filename|escapejs}}')"></td>
      </tr>
      <tr>
        <td>Right:</td>
        <td>
          <select name="right" id="right">
            {%for p in patchsets%}
            <option value="{{p.key.id}}" {%ifequal patchset.key.id p.key.id%}selected="selected"{%endifequal%}>Patch Set {{forloop.counter}}: {{p.message}}</option>
            {%endfor%}
          </select>
        </td>
      </tr>
    </table>
  </div>
</div>
<div style="clear: both;"></div>
<div class="error">
  <p>The selected patch doesn't exist in the selected patchset.</p>
  <p>Use the patchset chooser above or go back to the
    <a href="{%url codereview.views.show issue.key.id%}">issue page</a>.
  </p>
</div>
{%endblock%}

templates/exception.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
	<title>An Error Occurred - Code Review</title>
	<style>
	  body {
	    font-family: Arial, Helvetica, sans-serif;
	    background-color: #fff;
	  }
	  .technical {
	    color: #666;
	  }
	</style>
  </head>
  <body>
	<div style="font-weight:bold; font-size: 83%;">
	  <i>Rietveld</i> Code Review Tool
	</div>
	<div style="margin: 20px;">
	  <h1>Sorry, an error occurred...</h1>
	  <p>{{msg}}</p>
	  <p class="technical">Details: {{technical}}</p>
	  <p>Please post a message to the <a href="http://groups.google.com/group/codereview-discuss">discussion group</a> if you have any questions.</p>
	</div>
  </body>
</html>

templates/file_navigation.html
{%if patch.prev_with_comment%}
<a id="prevFileWithComment"
   href="{%ifequal view_style 'patch'%}{%url codereview.views.patch issue.key.id,patchset.key.id,patch.prev_with_comment.key.id%}{%else%}{%url codereview.views.diff issue.key.id,patchset.key.id,patch.prev_with_comment.filename%}{%endifequal%}{%urlappend_view_settings%}">
&laquo; {{patch.prev_with_comment.filename}}</a> ('K'){%else%}
<span class="disabled">&laquo; no previous file with comments</span>{%endif%}
|
{%if patch.prev%}
<a id="prevFile"
   href="{%ifequal view_style 'patch'%}{%url codereview.views.patch issue.key.id,patchset.key.id,patch.prev.key.id%}{%else%}{%url codereview.views.diff issue.key.id,patchset.key.id,patch.prev.filename%}{%endifequal%}{%urlappend_view_settings%}">
&laquo; {{patch.prev.filename}}</a> ('k'){%else%}
<span class="disabled">&laquo; no previous file</span>{%endif%}
|
{%if patch.next%}
<link rel="prerender"
   href="{%ifequal view_style 'patch'%}{%url codereview.views.patch issue.key.id,patchset.key.id,patch.next.key.id%}{%else%}{%url codereview.views.diff issue.key.id,patchset.key.id,patch.next.filename%}{%endifequal%}{%urlappend_view_settings%}"></link>
<a id="nextFile"
   href="{%ifequal view_style 'patch'%}{%url codereview.views.patch issue.key.id,patchset.key.id,patch.next.key.id%}{%else%}{%url codereview.views.diff issue.key.id,patchset.key.id,patch.next.filename%}{%endifequal%}{%urlappend_view_settings%}">
{{patch.next.filename}} &raquo;</a> ('j'){%else%}
<span class="disabled">no next file &raquo;</span>{%endif%}
|
{%if patch.next_with_comment%}
<a id="nextFileWithComment"
   href="{%ifequal view_style 'patch'%}{%url codereview.views.patch issue.key.id,patchset.key.id,patch.next_with_comment.key.id%}{%else%}{%url codereview.views.diff issue.key.id,patchset.key.id,patch.next_with_comment.filename%}{%endifequal%}{%urlappend_view_settings%}">
{{patch.next_with_comment.filename}} &raquo;</a> ('J'){%else%}
<span class="disabled">no next file with comments &raquo;</span>{%endif%}

templates/issue_pagination.html
{%extends "issue_base.html"%}
{%block body%}
<script language="JavaScript" type="text/javascript"><!--
  document.onkeydown = M_dashboardKeyDown;	
-->
</script>
<h2>{%block subtitle%}Issues{%endblock%}</h2>

<div class="issue-list">
  <div class="pagination">
    {%if newest%}
      <a class="novisit" href="{{newest}}">&laquo; Newest</a>
    {%endif%}
    {%if prev%}
      <a class="novisit" href="{{prev}}">&lsaquo; Newer</a>
    {%endif%}
    <b>{{first}}{%if last%} - {{last}}{%endif%}</b>
    {%if next%}<a class="novisit" href="{{next}}">{{nexttext}} &rsaquo;</a>
    {%else%}<span style="color:gray">{{nexttext}} &rsaquo;</span>{%endif%}
  </div>

  <table id="queues">
    {%if not issues%}
      <tr><td colspan="9"><span class="disabled">(None)</span></td></tr>
    {%else%}
      {%include "issue_heading.html"%}
      {%for issue in issues%}
        {%include "issue_row.html"%}
      {%endfor%}
    {%endif%}
  </table>

  <div class="pagination">
    {%if newest%}
      <a class="novisit" href="{{newest}}">&laquo; Newest</a>
    {%endif%}
    {%if prev%}
      <a class="novisit" href="{{prev}}">&lsaquo; Newer</a>
    {%endif%}
    <b>{{first}}{%if last%} - {{last}}{%endif%}</b>
    {%if next%}<a class="novisit" href="{{next}}">{{nexttext}} &rsaquo;</a>
    {%else%}<span style="color:gray">{{nexttext}} &rsaquo;</span>{%endif%}
  </div>

</div>

<script language="JavaScript" type="text/javascript"><!--
var dashboardState = new M_DashboardState(window,'issue');
-->
</script>
{%endblock%}

templates/issue_row.html
<tr {%if issue.num_drafts%}style="color:red"{%endif%} name="issue">
  <td class="first" width="14"><img src="{{media_url}}closedtriangle.gif" 
    style="visibility: hidden;" width="12" height="9" /></td>
  <td width="34" align="left" style="white-space: nowrap">{%include "issue_star.html"%}
{%if issue.edit_allowed and not issue.closed%}
<span class="issue-close" id="issue-close-{{issue.key.id}}">
    <a href="javascript:M_closeIssue({{issue.key.id}})">
      <img src="{{media_url}}close.gif" title="Close This Issue" width="15"
      height="15" border="0"></a>
</span>
{%endif%}</td>
  <td align="right"><div class="subject"><a class="noul"
         href="{%url codereview.views.show issue.key.id%}">{{issue.key.id}}</a>
     </div>
  </td>
  <td>
    <div class="subject">
      <a class="noul" href="{%url codereview.views.show issue.key.id%}"
      id="issue-title-{{issue.key.id}}">{{issue.subject}}</a>
      {%if issue.closed and not closed_issues %} (Closed) {%endif%}
    </div>
  </td>
  <td><div class="users">{{issue.owner|show_user}}</div></td>
  <td><div class="users">{{issue.reviewers|show_users}}</div></td>
  <td align="center">{%firstof issue.num_comments%}</td>
  <td align="center"><b>{%firstof issue.num_drafts%}</b></td>
  <td class="last"><div class="date">{{issue.modified|timesince}}</div></td>
</tr>

templates/issue_star.html
<span id="issue-star-{{issue.key.id}}">
  {%if issue.is_starred%}
    <a href="javascript:M_removeIssueStar({{issue.key.id}})">
      <img src="{{media_url}}star-lite.gif" width="15" height="15" border="0"></a>
  {%else%}
    {%if request.user%}
      <a href="javascript:M_addIssueStar({{issue.key.id}})">
	<img src="{{media_url}}star-dark.gif" width="15" height="15" border="0"></a>
    {%endif%}
  {%endif%}
</span>

templates/patch.html
{%extends "issue_base.html"%}
{% load fogbugz %}
{%block body%}

<script language="JavaScript" type="text/javascript"><!--
document.onkeydown = M_keyDown;
{%if user%}
logged_in = true;
{%else%}
logged_in = false;
login_warned = false;
{%endif%}
// -->
</script>

{%if user%}
<!-- Form used by in-line comment JS; XXX filled in by JS code -->
<form id="dainlineform" style="display: none;"
      action="{%url codereview.views.inline_draft%}" method="post">
  <div class="comment-border">
    <input type="hidden" name="snapshot" value="XXX">
    <input type="hidden" name="lineno" value="XXX">
    <input type="hidden" name="side" value="XXX">
    <input type="hidden" name="issue" value="{{issue.key.id}}">
    <input type="hidden" name="patchset" value="{{patchset.key.id}}">
    <input type="hidden" name="patch" value="{{patch.key.id}}">
    <textarea name="text" cols="60" rows="5"></textarea><br>
    <input type="submit" name="save" value="Save"
           onclick="return M_submitInlineComment(this.form);">
    <input type="reset" name="cancel" value="Cancel"
           onclick="M_removeTempInlineComment(this.form)">
  </div>
  <div class="comment-border" style="padding: 0pt;"></div>
</form>
<a id="resizer" style="display:none;cursor:pointer"><img src="{{media_url}}zippyplus.gif"></a>
{%endif%}

<div style="float: left;">
  <h2 style="margin-bottom: 0em; margin-top: 0em;">Unified Diff: {{patch.filename}}</h2>
  {%ifnotequal patch.nav_type "patch"%}
    <span style="color:red">Side-by-side diff isn't available for this file because of its large size.</span>
  {%endifnotequal%}
  <div style="margin-top: .2em;">{%include "issue_star.html"%}
    <b>Issue <a href="{%url codereview.views.show issue.key.id%}" onmouseover="M_showPopUp(this, 'popup-issue');" id="upCL">{{issue.key.id}}</a>:</b>
  {{issue.subject}} {%if issue.closed %} (Closed) {%endif%} <a href="{{issue|fogbugz_case_url}}" target="_blank">see Fogbugz case</a>
  {%if issue.base%}<span class="extra">Base URL: {{issue.base}}</span>{%endif%}</div>
  <div style="margin-top: .4em;">
    <b>Patch Set: {%if patchset.message%}{{patchset.message}}{%endif%}</b>
    <span class="extra">
    Created {{patchset.created|timesince}} ago
    {%if patchset.url%},
    Downloaded from: <a href="{{patchset.url}}">{{patchset.url}}</a>
    {%endif%}
    </span>
  </div>
  <div style="margin-top: .4em;" class="help">
    Use n/p to move between diff chunks;
    N/P to move between comments.
    {%if user%}
    Double-click a line to add a draft in-line comment.
    <br><span style="color:red">Draft comments are only viewable by you;</span>
    use <a href="{%url paylogic.views.publish issue.key.id%}" class="novisit">Publish+Mail Comments</a> ('m') to let others view them.
    {%else%}
    Please Sign in to add in-line comments.
    {%endif%}
  </div>
</div>
{%if column_width and context%}
  <input type="hidden" id="id_context" value="{{context}}" />
  <input type="hidden" id="id_column_width" value="{{column_width}}" />
{%endif%}
<div style="float: right; color: #333333; background-color: #eeeeec; border: 1px solid lightgray; -moz-border-radius: 5px 5px 5px 5px; padding: 5px;">
  <div>
    Jump to: <select onchange="M_jumpToPatch(this, {{issue.key.id}}, {{patchset.key.id}}, true);">
      {% for jump_patch in patchset.patch_set %}
        <option value="{{jump_patch.key.id}}"
         {%ifequal jump_patch.key.id patch.key.id%} selected="selected"{%endifequal%}>{{jump_patch.filename}}</option>
      {% endfor %}
    </select>
  </div>
  {%if not patch.no_base_file%}
  <div style="margin-top: 5px;">
    <a href="{%url codereview.views.diff issue.key.id,patchset.key.id,patch.filename%}{%urlappend_view_settings%}">
    View side-by-side diff with in-line comments</a>
  </div>
  {%endif%}
  <div style="margin-top: 5px;">
    <a href="{%url codereview.views.download_patch issue.key.id,patchset.key.id,patch.key.id%}"
       title="Download patch for {{patch.filename}}">
      Download patch
    </a>
  </div>
  {%if user%}
  <div style="margin-top: 5px;">
    <a class="novisit" href="{%url paylogic.views.publish issue.key.id%}">Publish+Mail
    Comments</a> ('m')
    |
    <a class="novisit" href="javascript:draftMessage.dialog_show()">Edit draft message</a> ('M')
  </div>
  {%endif%}
</div>
<div style="clear: both;"></div>

<div class="code" style="margin-top: 1.3em; display: table; margin-left: auto; margin-right: auto;">

<div class="codenav">
{%include "file_navigation.html"%} <br/>
<a href="javascript:M_expandAllInlineComments()">Expand Comments</a> ('e')
|
<a href="javascript:M_collapseAllInlineComments()">Collapse Comments</a> ('c')
|
<a name="show-all-inline"
   style="display:none"
   href="javascript:M_showAllInlineComments()">Show Comments</a>
<a name="hide-all-inline"
   href="javascript:M_hideAllInlineComments()">Hide Comments</a> ('s')
</div>

<div style="position:relative" id="table-top">

{%if patch.is_binary%}
<img src="{%url codereview.views.image issue.key.id,patchset.key.id,patch.key.id,1%}" />
{%else%}
<span id="hook-sel" style="display:none;"></span>

<table style="padding: 5px;" cellpadding="0" cellspacing="0" id="thecode"
       ondblclick="M_handleTableDblClick(event)"
       ontouchstart="M_handleTableTouchStart(event)"
       ontouchend="M_handleTableTouchEnd(event)">
{%for row in rows%}{{row|safe}}{%endfor%}
</table>
{%endif%}

</div>
<div class="codenav">
{%include "file_navigation.html"%}
</div>
</div>

<script language="JavaScript" type="text/javascript"><!--
var old_snapshot = "old";
var new_snapshot = "new";
var intraLineDiff = new M_IntraLineDiff();
var hookState = new M_HookState(window);
hookState.updateHooks();


// -->
</script>

{%include "draft_message.html"%}

{%endblock%}

templates/user_popup.html
<b>{{user.email}} ({{user.nickname}})</b>
<p>
issues created: {{num_issues_created}} <br/>
issues reviewed: {{num_issues_reviewed}}
</p>